apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-private-repo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: envs/dev
    repoURL: git@github.com:aws-samples/eks-blueprints-workloads.git
    targetRevision: HEAD